apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: ks-dev
      server: https://35.193.20.230
    k8sVersion: v1.10.7
    path: default
kind: ksonnet.io/app
libraries:
  incubator/redis:
    name: redis
    registry: incubator
    version: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
name: guestbook
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
